theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"

[keys.insert]
C-s = ":w"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
# hidden = false

[editor.statusline]
left = ["mode", "version-control", "spinner"]
center = ["file-base-name"]
right = ["diagnostics", "position", "file-encoding", "file-type"]