require('lspkind').init({
    mode = 'symbol_text',
    preset = 'codicons',
    symbol_map = {
        Text = '',
        Method = 'ƒ',
        Function = '',
        Constructor = '',
        Field = "ﰠ",
        Variable = '',
        Class = '',
        Interface = 'ﰮ',
        Module = '',
        Property = '',
        Unit = '',
        Value = '',
        Enum = '了',
        Keyword = '',
        Snippet = '﬌',
        Color = '',
        File = '',
        Reference = "",
        Folder = '',
        EnumMember = '',
        Constant = '',
        Struct = '',
        Event = "",
        Operator = "",
        TypeParameter = ""
    },
})
