# Start external programs

[[startProcess]]
command = "pkill nimdow"
keys = [ "Delete" ]
modifiers = [ "control", "alt" ]

[[startProcess]]
command = "$BROWSER"
keys = [ "i" ]
modifiers = [ "alt" ]

[[startProcess]]
command = "rofi -show drun -theme slate"
keys = [ "d" ]
modifiers = [ "alt" ]

[[startProcess]]
command = "terminator"
keys = [ "Return" ]
modifiers = [ "alt" ]

[autostart]
exec = [
  "xsetroot -cursor_name left_ptr",
  "menu_nim",
  "compton",
  "redshift-gtk -l 20.33:-102.76",
  "setxkbmap dvorak",
  "lxpolkit",
  "volumeicon",
  "feh --bg-scale ~/Pictures/wallper/mikael.jpg",
]

[settings]
  # Window settings
  gapSize = 8
  borderWidth = 3
  borderColorUnfocused = "#282a36"
  borderColorFocused = "#1bc8aa"
  borderColorUrgent = "#ff5775"
  # Bar settings
  barHeight = 20
  barBackgroundColor = "#021626"
  barForegroundColor = "#f8f8f2"
  barSelectionColor = "#e4d28b"
  barUrgentColor = "#fc504d"
  barFonts = [
    "monospace:size=10:anialias=false",
    "NotoColorEmoji:size=10:anialias=false"
  ]
  # General settings
  loggingEnabled = false

# Window manager controls
[controls]
  [controls.reloadConfig]
  keys = [ "r" ]
  modifiers = [ "alt", "shift" ]

  [controls.focusPrevious]
  keys = [ "h" ]
  modifiers = [ "alt" ]

  [controls.focusNext]
  keys = [ "l" ]
  modifiers = [ "alt" ]

  [controls.moveWindowPrevious]
  keys = [ "h" ]
  modifiers = [ "alt", "shift" ]

  [controls.moveWindowNext]
  keys = [ "l" ]
  modifiers = [ "alt", "shift" ]

  [controls.toggleFullscreen]
  keys = [ "f" ]
  modifiers = [ "alt" ]

  [controls.destroySelectedWindow]
  keys = [ "c" ]
  modifiers = [ "alt", "shift" ]

  [controls.moveWindowToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "alt", "shift" ]

  [controls.goToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "alt" ]

  [controls.goToPreviousTag]
  keys = [ "w" ]
  modifiers = [ "alt" ]

  [controls.toggleTagView]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "alt", "control" ]

  [controls.toggleWindowTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "alt", "shift", "control" ]

  [controls.focusPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "alt" ]

  [controls.focusNextMonitor]
  keys = [ "period" ]
  modifiers = [ "alt" ]

  [controls.moveWindowToPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "alt", "shift" ]

  [controls.moveWindowToNextMonitor]
  keys = [ "period" ]
  modifiers = [ "alt", "shift" ]

  [controls.increaseMasterCount]
  keys = [ "z" ]
  modifiers = [ "alt" ]

  [controls.decreaseMasterCount]
  keys = [ "x" ]
  modifiers = [ "alt" ]

  [controls.toggleFloating]
  keys = [ "space" ]
  modifiers = [ "alt" ]

  [controls.jumpToUrgentWindow]
  keys = [ "u" ]
  modifiers = [ "alt" ]

