#!/bin/bash

red=$'\e[31m'
green=$'\e[32m'
blue=$'\e[34m'
magenta=$'\e[35m'
cyan=$'\e[36m'
white=$'\e[0m'

function get_cpu_temp {
    CPU_TEMP=$(sensors | awk '/^Package/ {printf $4}')
}

function get_mem_use {
    RAM_USE=$(free -h | awk '/^Mem:/ {print $3 "/" $2}' | sed 's/Gi//g')
}

function get_swap_use {
	SWAP_USE=$(free -h | awk '/^Swap:/ {print $3 "/" $2}' | sed 's/Gi//g')
}

function get_cpu_use {
    read cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))
    sleep 0.5
    read cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))
    cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
    CPU_USE=$cpu
}

ram=$(free -h | awk '/^Mem:/ {print $3 "/" $2}' | sed 's/Gi//g')

while true; do
    xsetroot -name "${ram} | $(date +"${cyan}%F ${white}%R")"
	sleep 2
done 
